kotlin.code.style=official

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M" -XX:+HeapDumpOnOutOfMemoryError
#org.gradle.daemon=false
org.gradle.parallel=false

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Compose
org.jetbrains.compose.experimental.wasm.enabled=true
compose.resources.always.generate.accessors=true

#MPP

#Development
development=true
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false