name: build-and-delpoy
run-name: Build & deploy to Github Pages
on:
  push:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-web:
    name: "Build for Web"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties (idk about this)
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build for web
        run: ./gradlew wasmJsBrowserDistribution

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: Browser distribution
          path: './composeApp/build/dist/wasmJs/productionExecutable/'

      - name: Deploy to GithubPages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: './composeApp/build/dist/wasmJs/productionExecutable/'
          branch: github-pages

# absolute jdk path is bad
# 'org.jetbrains.compose.desktop.application.tasks.AbstractCheckNativeDistributionRuntime' property 'jdkHome' specifies directory '/usr/lib/jvm/java-17-openjdk' which doesn't exist.
#
 #  build-dektop:
 #    name: "Build for Desktop ${{ matrix.os }}"
 #    strategy:
 #      matrix:
 #        os: [ubuntu-latest, macos-latest, windows-latest]
 #    runs-on: ${{ matrix.os }}
 #    permissions:
 #      contents: write
 #    steps:
 #      - name: Checkout
 #        uses: actions/checkout@v4
 #
 #      - name: Validate Gradle Wrapper
 #        uses: gradle/wrapper-validation-action@v1
 #
 #      - name: Copy CI gradle.properties (idk about this)
 #        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
 #
 #      - name: Set up JDK 17
 #        uses: actions/setup-java@v4
 #        with:
 #          distribution: 'zulu'
 #          java-version: 17
 #
 #      - name: Setup Gradle
 #        uses: gradle/gradle-build-action@v2
 #
 #      - name: Gradle build for web
 #        run: ./gradlew composeApp:createDistributable
 #
 #      - name: Upload build output
 #        uses: actions/upload-artifact@v4
 #        with:
 #          name: Desktop distribution
 #          path: './composeApp/build/compose/binaries/**/app/com.pierbezuhoff.dodeclusters/bin/'
